### ISSUE TITLE
Use requests instead of urllib

### ISSUE THREAD

**Issue by FranklinYu** [MacDownApp/macdown-site#17]
See https://github.com/HandBrake/HandBrake/issues/2216#issuecomment-527114519

This affects https://github.com/MacDownApp/macdown-site/blob/master/packages/lektor-macdown/lektor_macdown/utils.py

**Comment by uranusjr** [comment]
Gosh, WTF Apple.

**Comment by FranklinYu** [comment]
Or we can require user to avoid Python3 from either Xcode or CLT? IIUC they can still use Python from:

- Homebrew (most popular?)
- MacPorts
- official installer from PSF
- pyenv

**Comment by uranusjr** [comment]
I’m OK either way. It’s never a bad idea to use requests instead of urllib, but I’m not doing it myself if there are alternatives :p
