### ISSUE TITLE
TOC not working in Version 0.6.5d56 (842) MacDown

### ISSUE THREAD

**Issue by varuns23** [MacDownApp/macdown-site#2]
I am using OS X Sierra with MacDown Version 0.6.5d56 (842). [toc] does not seem to work.
Please fix it.

Thanks

**Comment by franklinyu** [comment]
This is not the right place. [Issue tracker is here](https://github.com/MacDownApp/macdown/issues).

In addition, try "Preferences -> Rendering -> Detect table of contents token".
