### ISSUE TITLE
Versions Out of Order in Testing Channel

### ISSUE THREAD

**Issue by spencermathews** [MacDownApp/macdown-site#8]
The versions are out of order in the [Testing Channel](https://macdown.uranusjr.com/history/testing/) page. In particular, the newest version (0.7.2d137) is at the very bottom, making it very unintuitive to locate. Aside from just making sense, this would go a long way toward alleviating the frustration of users forced to manually install the latest testing version while the auto-updater is broken (MacDownApp/macdown#900, MacDownApp/macdown#1029).

**Comment by qudade** [comment]
I tried to fix this - at first sight it's because the latest testing version has the first four-digit release number.

However, whenever I build the site on my Mac the order is correct - even with older versions of Lektor.

Maybe the site just has to be rebuilt?

**Comment by uranusjr** [comment]
Just did that and it doesn’t fix it. This is very strange. Maybe I can change some configuration on Netlify. What version of Python/pip/Lektor etc. are you using to get the correct order?

**Comment by qudade** [comment]
Nothing exciting:
```
(venv) puk-2:macdown-site jhereth$ clear
(venv) puk-2:macdown-site jhereth$ which python
/Users/jhereth/repos/macdown-site/venv/bin/python
(venv) puk-2:macdown-site jhereth$ python --version
Python 3.7.3
(venv) puk-2:macdown-site jhereth$ pip --version
pip 19.1.1 from /Users/jhereth/repos/macdown-site/venv/lib/python3.7/site-packages/pip (python 3.7)
(venv) puk-2:macdown-site jhereth$ which lektor
/Users/jhereth/repos/macdown-site/venv/bin/lektor
(venv) puk-2:macdown-site jhereth$ lektor --version
Lektor, version 3.0
```

running on MacOS.

Probably it's not the version but the underlying OS - netlify is probably not running on macos. 

in https://github.com/qudade/macdown-site/tree/qudade_fix_release_order you find a branch where I left-padded the 3-digit-release numbers with 0. Maybe you want to try if this fixes the issue?

**Comment by FranklinYu** [comment]
In my environment (Ubuntu) I rebuild and the order didn't change on a fresh build. My `pip freeze`:

```text
argh==0.26.2
asn1crypto==0.24.0
Babel==2.6.0
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
Click==7.0
cryptography==2.6.1
ExifRead==2.1.2
Flask==1.0.3
idna==2.8
inifile==0.4
invoke==1.2.0
itsdangerous==1.1.0
Jinja2==2.10.1
Lektor==3.1.3
MarkupSafe==1.1.1
mistune==0.8.4
pathtools==0.1.2
pkg-resources==0.0.0
py-mini-racer==0.1.18
pycparser==2.19
pyOpenSSL==19.0.0
pytz==2019.1
PyYAML==5.1
requests==2.22.0
six==1.12.0
urllib3==1.25.3
watchdog==0.9.0
Werkzeug==0.15.4
```

**Comment by qudade** [comment]
@uranusjr Trying again, I see the same error. I'm afraid my above statement was wrong, at least I cannot reproduce the successful build. Sorry.

**Comment by qudade** [comment]
@uranusjr @FranklinYu Sorry for the red herring. As far as I can tell the reason is a wrong type definition in `release.ini` (see #14 ). 

When comparing build numbers `lektor` coerces them to strings and then you have of course 1007 before 157 long before 996.

You probably have to [add `build_number` as new field type](https://www.getlektor.com/docs/plugins/howto/#adding-new-field-types).

My workaround in #14 maps build numbers to floats, but this will change anchors in the release history and will display a `.0` suffix for "integer" build numbers (I couldn't find a nice way to fix this output problem).

Hope this helps.

**Comment by FranklinYu** [comment]
> When comparing build numbers `lektor` coerces them to strings

Are you sure? I was looking at

https://github.com/MacDownApp/macdown-site/blob/c479c21851de6a40c68c63d3f17cdf8b1261c96c/packages/lektor-sparkle/lektor_sparkle/__init__.py#L52

**Comment by qudade** [comment]
Lektor's `coerce` comes through [here](https://github.com/lektor/lektor/blob/093c1a3116722059a65d74b6aa17d72e99a25d16/lektor/db.py#L112). 

On the other hand BuildNumberType values [are Strings](https://github.com/MacDownApp/macdown-site/blob/c479c21851de6a40c68c63d3f17cdf8b1261c96c/packages/lektor-sparkle/lektor_sparkle/__init__.py#L16-L18] so it's no coercion in the strict sense.

**Comment by qudade** [comment]
I updated #14. Hope that help.

**Comment by qudade** [comment]
@uranusjr @FranklinYu #14 seems to fix the issue for good. Anything else I should add?
