### ISSUE TITLE
Support for Markdown Front Matter

### ISSUE THREAD

**Issue by brycekunkel** [MacDownApp/macdown-site#9]
Would love to see support for Metadata through Markdown Front Matter. 

https://jekyllrb.com/docs/front-matter/

**Comment by FranklinYu** [comment]
Front matter *is* supported. May not be enabled by default; go though preferences menu.

**Comment by brycekunkel** [comment]
Got it. Thanks for that note. I'm still seeing that the Front Matter renders, just in a table format. Is this expected behavior?
![screen shot 2019-02-13 at 9 55 03 am](https://user-images.githubusercontent.com/22450894/52724697-74470000-2f75-11e9-8585-899caa8c5f0f.png)

**Comment by brycekunkel** [comment]
Just now realizing that this is on the Macdown site repository, I'll repost in the Macdown app repository.

**Comment by FranklinYu** [comment]
Yes this is expected. What would you expect otherwise? Please describe.

**Comment by brycekunkel** [comment]
I researched a little more and yes, that issue is what I am referring to. In my opinion, the front matter table should only show in the MD side of things, not on the preview.
